### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by infoble** [CREASIG/QBANO#10]
Bonjour,
cette extension m'est très utile depuis des années mais j'ai aujourd'hui l'erreur python suivante : 
 
```
File "C:/Users/jacques-b/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QBano\QBano_dialog.py", line 210, in coordonnees
              response = urllib.request.urlopen('http://api-adresse.data.gouv.fr/search/?' + url+'&limit=1')
             AttributeError: module 'urllib' has no attribute 'request'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/jacques-b/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QBano\QBano_dialog.py", line 173, in geocoder
              coordonnees = self.coordonnees(adresse_complete, cp,insee, city)
              File "C:/Users/jacques-b/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QBano\QBano_dialog.py", line 221, in coordonnees
              except urllib2.HTTPError as e:
             NameError: name 'urllib2' is not defined
```
             
J'ai désactivé toutes les autres extensions mais l'erreur persiste.
Windows 10 pro 64bits, Qgis 3.10.10
Merci de votre aide

**Comment by infoble** [comment]
Après installation de la version 3.16 tout fonctionne à nouveau même sur la version 3.10. Peut-être un hasard...ou pas.

**Comment by CREASIG** [comment]
Bonjour, je viens de tester sur la 3.10.1 et ça fonctionne.

Essayez de réinstaller qgis

**Comment by infoble** [comment]
Donc ce n'était pas un hasard que ça fonctionne après avoir installé la dernière version... Merci.
